# Generated by Django 4.2.27 on 2026-05-24 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('occupation', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('fellowship', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.attendee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.event')),
            ],
            options={
                'unique_together': {('event', 'attendee')},
            },
        ),
    ]
