# Generated by Django 5.1.1 on 2024-11-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_leadership'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadership',
            name='role',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
