# Generated by Django 4.2.27 on 2026-05-24 22:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_attendee_eventattendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendee',
            options={'verbose_name': 'Attendee', 'verbose_name_plural': 'Attendees'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventattendance',
            options={'verbose_name': 'Event Attendance', 'verbose_name_plural': 'Event Attendances'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='leadership',
            options={'verbose_name': 'Leadership Record', 'verbose_name_plural': 'Leadership Records'},
        ),
        migrations.AddField(
            model_name='attendee',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendee',
            name='fellowship',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Fellowship / Cell Group'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='occupation',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='phone_number',
            field=models.CharField(max_length=30, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='uploads/event/', verbose_name='Event Image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Event Name'),
        ),
        migrations.AlterField(
            model_name='eventattendance',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_attended', to='church.attendee'),
        ),
        migrations.AlterField(
            model_name='eventattendance',
            name='checked_in_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Checked In At'),
        ),
        migrations.AlterField(
            model_name='eventattendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='church.event'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(upload_to='uploads/group/', verbose_name='Group Image'),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_second',
            field=models.BooleanField(default=False, verbose_name='Is Second Group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Group Name'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='bio',
            field=models.TextField(verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='image',
            field=models.ImageField(upload_to='uploads/leadership/', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='role',
            field=models.CharField(max_length=250, verbose_name='Role / Position'),
        ),
    ]
