# Generated by Django 5.1.1 on 2024-11-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_leadership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadership',
            name='bio',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
