# Generated by Django 5.2.6 on 2025-09-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tithe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tithe',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
