# Generated by Django 5.2.6 on 2025-09-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tithe', '0002_alter_tithe_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avartar',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('REGULAR_USER', 'regular_user')], default='regular_user', max_length=20),
        ),
    ]
