# Generated by Django 5.2.6 on 2025-12-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tithe', '0003_remove_customuser_avartar_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('REGULAR_USER', 'regular_user')], default='REGULAR_USER', max_length=20),
        ),
    ]
